logging:
    level:
        tk.mybatis: info
        com.huizhiframework.security: info
        com.huizhiframework.security: debug
spring:
    profiles: dev
    application:
        name: hz-integral-web
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/data_manage?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
mybatis:
    mapper-locations: "classpath*:mapper/**/*.xml"
server:
    port: 8762
    servlet:
      context-path: /api/
auth:
  user:
    token-header: Authorization
    expire: 86400
    rsa-secret: xx1WET12^%3^(WE45

# 配置swagger
swagger:
    enabled: true
    base-package: com.huizhiframework.security.integral.web
    title: hz-admin
    version: 1.0.0.SNAPSHOT
    description: 管理后端服务
    contact:
        name: admin

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
